#!/usr/bin/python3

import os
import click

from core.config import SameSpeciesConfigLoader
from core.config_mapper import SameSpeciesConfigMapper
from core.rest_query import get_all_maps, query_single_species
from core.results_parser import json_results_to_csv

def process_version():
    version = os.getenv('VERSION', None)
    if version:
        click.echo(f'Version {version}')

@click.command()
@click.option('--config', '-c', required=True, type=click.Path(exists=True), help='Input configuration file')
@click.option('--output', '-o', required=True, type=click.Path(), help='Output directory')
def process_data(config, output):
    process_version()

    click.echo(f'Processing configuration from {config} and saving results to {output}')

    config_loader = SameSpeciesConfigLoader(config)

    click.echo(config_loader)

    click.echo('Getting species and interactomes...')
    species_map, interactomes_map, predictomes_map = get_all_maps()
    config_mapper = SameSpeciesConfigMapper(
        config_loader, species_map, interactomes_map, predictomes_map)

    click.echo('Querying EvoPPI...')
    results = query_single_species(config_mapper)

    if results:
        json_results_to_csv(results, config_loader.get_format(), output)

if __name__ == '__main__':
    process_data()
